name: 'NetRise Uploader'
description: 'Upload a software artifact to NetRise for processing.'
inputs:
  config-path:
    description: 'Path to the NetRise configuration file'
    required: true

  artifact-path:
    description: 'Path to the software artifact to upload to NetRise'
    required: true

  name:
    description: 'Asset name'
    required: true

  manufacturer:
    description: 'Asset manufacturer'
    required: false

  model:
    description: 'Asset model'
    required: false

  version:
    description: 'Asset version'
    required: false
  
outputs:
  upload-id:
    description: 'Unique upload ID for this upload operation'

  asset-id:
    description: "The asset's ID in the system"

  uploaded:
    description: 'Boolean indicating if the upload is complete'
  
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Setup ENV Variables
      run: |
        echo "CONFIG_PATH=${{ inputs.config-path }}" >> $GITHUB_ENV
        echo "ARTIFACT_PATH=${{ inputs.artifact-path }}" >> $GITHUB_ENV
      shell: bash
    
    - name: Submit Artifact
      run: python submit.py
      shell: bash

