on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  submit_artifact:
    runs-on: ubuntu-latest
    name: Submits an artifact to NetRise
    steps:
      - uses: actions/checkout@v4
      - uses: puddlepep/netrise-gh-action@v1
        with:

          # auth info
          client-id: ${{ secrets.NETRISE_CLIENT_ID }}
          client-secret: ${{ secrets.NETRISE_CLIENT_SECRET }}
          organization-id: ${{ secrets.NETRISE_ORGANIZATION_ID }}
          token-url: 'https://authn.turbine.netrise.io/oauth/token'
          audience: 'https://prod.turbine.netrise.io/'
          endpoint: 'https://apollo.turbine.netrise.io'

          # asset info
          artifact-path: './firmware.bin'
          name: 'github action firmware test'
          manufacturer: 'b'
          model: 'c'
          version: '1.0.0'
