on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Artifact Submitter Testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
        shell: bash

      - id: submit-artifact-test
        run: python tests.py
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          TOKEN_URL: ${{ secrets.TOKEN_URL }}
          AUDIENCE: ${{ secrets.AUDIENCE }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
      
