
on: [push, workflow_dispatch]

jobs:
  submit_artifact:
    runs-on: ubuntu-latest
    name: Submits an artifact to NetRise
    steps:
      - uses: puddlepep/netrise-gh-action@v1

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - uses: actions/checkout@v4
#       - id: foo
#         uses: puddlepep/netrise-gh-action@
#         with:
#           who-to-greet: 'pep!'
#       - run: echo random-number "$RANDOM_NUMBER"
#         shell: bash
#         env:
#           RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
