
on: [push, workflow_dispatch]

jobs:
  submit_artifact:
    runs-on: ubuntu-latest
    name: Submits an artifact to NetRise
    steps:
      - uses: actions/checkout@v4
      - uses: puddlepep/netrise-gh-action@v1
        with:
          config-path: './config.yaml'
          artifact-path: './firmware.bin'
          name: 'github action firmware test'
          manufacturer: 'b'
          model: 'c'
          version: '1.0.0'
